config/routes.rb
Hashmap::Application.routes.draw do
  root to: "maps#index"

  get "signup" => "users#new", as: "signup"
  get "signin" => "sessions#new", as: "signin"
  get "signout" => "sessions#destroy", as: "signout"

  resources :users, only: [:new, :show, :create, :destroy] do
    resources :collections do
      resources :collection_tags, only: [:new, :create] 
    end
  end

  resources :maps do
    collection {post :sort} 
  end

  resources :sessions, only: [:index, :new, :create, :destroy]
  resources :geomarkers do
    resources :comments
  end
  resources :friendships
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :collectionTags
  before_save :set_position

  private

  def set_position
    self.position ||= 1 + (eval("#{self.class.to_s}.maximum(:position)").to_i || 0)
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_filter :load_user

  def index
    user = User.find(params[:user_id])
    @collections = user.collections.load
  end

  def new
   @collection = @user.collection.build
  end

  def create
    @collection = @user.collections.create(collection_params)
    create_tags(@collection, params[:tag_list])
    @collection.user_id = current_user.id if current_user
    respond_to do |format|
      if @collection.save
        format.html { render "show" }
        format.js
      else
        format.html { render "new" }
      end
    end
  end

  def show
    user = User.find(params[:user_id])
    @collection = user.collections.find(params[:id])
  end

  def edit
    @collection = @user.collections.find(params[:id])
  end

  def update
    @collection = @user.collections.find(params[:id])
    if @collection.update_attributes(collection_params)
      redirect_to user_collection_path(@user.id, @collection.id)
    else
      render "edit"
    end
  end
  
  private
  
  def collection_params
    params.require(:collection).permit(:user_id, :name, :description)
  end

  def load_user
    @user = current_user
  end

  def create_tags(collection, tag_list)
    tag_list.split(", ").each do |tag|
      new_tag = collection.collectionTags.create!(name: tag, visibility: true)
    end
  end

end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_tag_list.js.erb
<% @collection.collectionTags.each do |tag| %>
  <li data-tag="<%= tag.name %>" data-show="enabled" class="sortable-active"><a><span class='handle'><i class='fa fa-sort'></i></span><i class="tag-eye fa fa-eye"></i><span><%= tag.name %></span></a></li>
<% end %>
<li class="tag-form" style="display: none">
  <span>
    <div>
      <%= render partial: "maps/tag_form", locals: {collection: @collection, user: @collection.user} %>
    </div>
  </span>
</li>
<li class="new-tag">
  <a><span>Add a Tag!</span></a>
</li>
  

app/views/collections/create.js.erb
var collection_length = <%= current_user.collections.length %>;
var collection_name = "<%= @collection.name %>";
var menu_id = "mm-m0-p" + collection_length;
var tag_list = "<%= j render(partial: 'tag_list') %>";
var collection_list_item = "<li data-collection= '" + collection_name + "' data-show='enabled' class='collection sortable-active' style='display: none;'><a class='mm-subopen' href=#" + menu_id + "></a><a><span class='handle'><i class='fa fa-sort'></i></span><i class='collection-eye fa fa-eye' data-show='enabled'></i><span>" + collection_name + "</span></a></li>"
var collection_menu = "<ul class='mm-list mm-panel' id='" + menu_id + "'><li class='mm-subtitle'><a class='mm-subclose' href='#mm-m0-p0'>" + collection_name + "</a></li>" + tag_list + "</ul>"
activeCollection = "#" + menu_id

$("#collection-form").before(collection_list_item);
$("#left-menu").append(collection_menu);
loadCollection(collection_name);

app/views/collections/edit.html.erb
<h1>Edit your collection!</h1>
<br>
<%= form_for @collection, url: user_collection_path(@user.id, @collection.id) do |f| %>
  <% if @collection.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @collection.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :tag_list %>
  <%= f.text_field :tag_list %>
  <%= f.submit "Submit", :class => "button" %>
<% end %>

app/views/collections/index.html.erb
<h1>Your Collections</h1>
<br>
<%= link_to "Start a collection", new_user_collection_path(@user) %>
<br>
<%= link_to "New Marker", new_geomarker_path %>
<% @collections.each do |collection| %>
  <p><%= link_to collection.name, user_collection_path(collection.user_id, collection.id) %></p>
  <p>Tags: <% collection.tags.each do |tag| %>
    <span><%= link_to tag.name, geomarkers_path(:tag => tag.name) %></span>
  <% end %></p>
  <p><%= collection.description %></p>
  <hr>
<% end %>

app/views/collections/new.html.erb
<h1>Create a collection!</h1>
<br>
<%= form_for @collection, url: user_collections_path(current_user.id) do |f| %>
  <% if @collection.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @collection.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :tag_list %>
  <%= f.text_field :tag_list %>
  <%= f.submit "Submit", :class => "button" %>
<% end %>

app/views/collections/show.html.erb
<h1><%= @collection.name %></h1>
<p><%= @collection.description %></p>
<p><% @collection.tags.each do |tag| %></p>
  <%= link_to tag.name, geomarkers_path(:tag => tag.name) %>
  <% end %>
</p>  

<%= link_to "Show all geomarkers", geomarkers_path(:tag => @collection.tag_list) %>