config/routes.rb
Hashmap::Application.routes.draw do
  root to: "maps#index"

  get "signup" => "users#new", as: "signup"
  get "signin" => "sessions#new", as: "signin"
  get "signout" => "sessions#destroy", as: "signout"

  resources :users, only: [:new, :show, :create, :destroy] do
    resources :collections do
      resources :collection_tags, only: [:new, :create] 
    end
  end

  resources :maps do
    collection {post :sort} 
  end

  resources :sessions, only: [:index, :new, :create, :destroy]
  resources :geomarkers do
    resources :comments
  end
  resources :friendships
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_filter :load_user

  def index
    @collections = @user.collections.order("position").load
  end

  def sort
    if params[:collection].present?
      params[:collection].each_with_index do |id, index|
        Collection.where(id: id).update_all(position: index+1)
      end
    elsif params[:collectionTag].present?
      params[:collectionTag].each_with_index do |id, index|
        CollectionTag.where(id: id).update_all(position: index+1)
      end
    end
    render nothing: true
  end

  private

  def load_user
    @user = current_user
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_collection_form.html.erb
<%= form_tag(user_collections_path(@user.id), method: "post",  remote: true,) do %>
  <%= text_field_tag 'collection[name]', nil, placeholder: "Collection name..." %>
  <%= text_field_tag 'tag_list', nil, placeholder: "Tags..." %>
  <%= submit_tag("Add") %>
<% end %>

<%= javascript_tag do %>
var current_user_id = <%= current_user.id %>
<% end %>

app/views/maps/_tag_form.html.erb
<%= form_tag(user_collection_collection_tags_path(user.id, collection.id), method: "post",  remote: true,) do %>
  <%= text_field_tag 'collection_tags[name]', nil, placeholder: "Things, stuff, plants, etc..." %>
  <%= submit_tag("Add") %>
<% end %>

app/views/maps/index.html.erb
  <div id="map">
  <a href="#" id="open-menu"><i class="open-menu fi-list"></i></a>
  <div class="form-container">
    <div class="geocoder-bar">
      <div class="geocoder-wrapper">
        <div class="addressSearch">
          <input id="address" type="text" value="Bermuda Triangle">
        </div>
        <div class="searchButton">
          <a href="#" id="addressLookup">Go!</a>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="control-menu">
  <a href="#wheel2" class="wheel-button ne">
    <span class="menu-open">#</i>  </span>
  </a>
  <ul id="wheel2" data-angle="NE" class="wheel">
    <li class="item" id="global-view"><a href="#home"><i class="icon fa fa-globe"></i></a></li>
    <li class="item" id="new-collection"><a href="#home"><i class="icon fa fa-umbrella"></i></a></li>
    <li class="item" id="new-marker-button" value="point and click"><a href="#home"><i class="icon fa fa-map-marker"></i></a></li>
    <li class="item" id="search-button" value="point and click"><a href="#home"><i class="icon fa fa-search"></i></a></li>
    <li class="item" id="user"><a href="#home"><i class="icon fa fa-user"></i></a></li>
    <li class="item" id="settings"><a href="#home"><i class="icon fa fa-cog"></i></a></li>
  </ul>
</div>

<nav id="left-menu">
  <ul class="sortable-collections" data-update-url="<%= sort_maps_path %>">
    <li>
      <span id="collection-header">
        <div><p>Your collections</p></div>
      </span>
    </li>
    <% @collections.each do |collection| %>
      <li data-collection="<%= collection.name %>" id="collection_<%= collection.id %>" data-show="disabled" class="collection sortable-active" >
        <a>
          <span class="handle"><i class="fa fa-sort"></i></span>
          <i class="collection-eye fa fa-eye-slash"></i>
          <span><%= collection.name %></span>
        </a>
        <ul class="sortable-tags" data-update-url="<%= sort_maps_path %>"> 
          <li>
            <span class="tag-header">
              <div><p>Item description to go here.</p></div>
            </span>
          </li>
          <% collection.collectionTags.each do |tag| %>
            <li data-tag="<%= tag.name %>" data-show="disabled" id="collectionTag_<%= tag.id%>" class="tag collectionTag sortable-active">
              <a>
                <span class="handle"><i class="fa fa-sort"></i></span>
                <i class="tag-eye fa fa-eye-slash"></i>
                <span><%= tag.name %></span></a>
            </li>
          <% end %>
            <li class="tag-form" style="display:none;">
              <span>
                <div>
                  <%= render partial: "tag_form", locals: {collection: collection, user: collection.user} %>
                </div>
              </span>
            </li>
            <li class="new-tag">
              <a><span>Add a Tag.</span></a>
            </li>
        </ul>
      </li>
    <% end %>
    <li id="collection-form">
      <span>
        <div>
          <%= render "collection_form" %>
        </div>
      </span>
    </li>
    <li id="new-collection">
      <a><span>Add a new collection.</span></a>
    </li>
    <li>
      <a href="<%= signout_path %>">Sign out.</a>
    </li> 
  </ul>
</nav>