config/routes.rb
Hashmap::Application.routes.draw do
  root to: "maps#index"

  get "signup" => "users#new", as: "signup"
  get "signin" => "sessions#new", as: "signin"
  get "signout" => "sessions#destroy", as: "signout"

  resources :users, only: [:new, :show, :create, :destroy] do
    resources :collections do
      resources :collection_tags, only: [:new, :create] 
    end
  end

  resources :maps do
    collection {post :sort} 
  end

  resources :sessions, only: [:index, :new, :create, :destroy]
  resources :geomarkers do
    resources :comments
  end
  resources :friendships
end

app/models/geomarker.rb
class Geomarker < ActiveRecord::Base
  acts_as_taggable
  acts_as_mappable :lat_column_name => :latitude,
                   :lng_column_name => :longitude
  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :tag_list, presence: true

  belongs_to :user
  has_many :comments
  has_many :users, :through => :comments

  def self.all_collection_tags(user)
    collections= user.collections
    results = []
    collections.each do |collection|
      collection.tag_list.each do |tag|
        results << tag
      end
    end
    results.join(', ')
  end

end

app/controllers/geomarkers_controller.rb
class GeomarkersController < ApplicationController
  def index
    if params[:tags].empty?
      @geomarkers = Geomarker.all
    else
      @geomarkers = Geomarker.tagged_with(params[:tags], :any => true)
    end
  end
  
  def show
    if params[:newMarker]
      @geomarker = Geomarker.order("created_at").reverse_order.find_by_user_id(current_user.id)
    else
      @geomarker = Geomarker.find(params[:id])
    end
    @user = User.find(@geomarker.user_id)
    @comment = @geomarker.comments.build

    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end
  
  def new
    @geomarker = Geomarker.new

    respond_to do |format|
      format.js
      format.html
    end
  end
  
  def create
    @geomarker = Geomarker.new(geomarker_params)
    @geomarker.user_id = current_user.id if current_user
    respond_to do |format|
      if @geomarker.save
        format.html { redirect_to geomarker_path(@geomarker) }
        format.js
      else
        format.html { render "new" }
        format.js
      end
    end
  end
  
  def edit
    @geomarker = Geomarker.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def update
    @geomarker = Geomarker.find(params[:id])
    if params[:geomarker][:remove_image].present? && params[:geomarker][:remove_image] == 1
      @geomarker.remove_image!
      @geomarker.save
      params[:geomarker][:remove_image] = nil
    end
    
    if params[:geomarker][:new_tags].present?
      params[:geomarker][:tag_list] = ""
      @geomarker.tag_list.each { |tag| params[:geomarker][:tag_list] << tag + ", " }
      params[:geomarker][:tag_list] = params[:geomarker][:tag_list] + params[:geomarker][:new_tags]
      params[:geomarker].delete("new_tags")
      @new_tags = true
    end
    
    if @geomarker.update_attributes(geomarker_params)
      respond_to do |format|
        format.html { redirect_to geomarker_path(@geomarker) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render "edit" }
        format.js
      end
    end
  end
  
  def destroy
    @geomarker = Geomarker.find(params[:id])
    @geomarker.destroy

    respond_to do |format|
      format.html { redirect_to geomarkers_path }
      format.js
    end
  end

  private
  def geomarker_params
    params.require(:geomarker).permit(:name, :description, :latitude, :longitude, :tag_list, :view, :sw, :ne, :remove_image, :image, :new_tags)
  end
end

app/helpers/geomarkers_helper.rb
module GeomarkersHelper
  
end

app/views/geomarkers/_comments.html.erb
<% @geomarker.comments.reverse.each do |comment| %>
  <% if comment.user != nil %>
    <div class="comment-wrapper">
      <hr>
      <% if comment.user_id == current_user.id %>
        <a class="deleteCommentButton" data-comment-id="<%= comment.id %>" href="#">Delete</a>
      <% end %>
      <p><b><%= comment.content %></b></p>
      <p>Posted by: <em><%= comment.user.username %></em></p>
      <p><em><%= comment.created_at.to_s(:long) %></em></p>
    </div>
  <% end %>
<% end %>

app/views/geomarkers/_edit.html.erb
<div id='geomarker-form-errors'></div>
<%= form_for @geomarker, :html => { :multipart => true,  :target => "blank_iframe" }, :remote => true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label "Description" %>
  <%= f.text_area :description %>
  <br>
  <%= f.label "Tags (a comma separated list)" %>
  <%= f.text_field :tag_list %>
  <br>
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <p>
    <label>
  <% if @geomarker.image.present? %>
    <%= image_tag @geomarker.image.thumb.to_s %>
    <br>
    <%= f.check_box :remove_image %>
    Remove Image
  <% else %>
    <section id='fileUploadSection'>
      <%= f.label :image %>
      <%= f.file_field :image %>
    </section>
  <% end %>
  </label>
    </p>
  <hr>
  <input id="cancelFormButton" class="button small" type="button" value="Cancel"/>
  <%= f.submit "Submit", :class => "button small", :id => "submit" %>
<% end %>

app/views/geomarkers/_geomarker_form.html.erb
<%= form_for @geomarker do |f| %>
  <% if @geomarker.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @geomarker.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :latitude %>
  <%= f.number_field :latitude, {in: -90..90, step: 0.01} %>
  <%= f.label :longitude %>
  <%= f.number_field :longitude, {in: -180..180, step: 0.01} %>
  <%= f.label :tag_list %>
  <%= f.text_field :tag_list %>
  
  <br>
  <%= f.submit "Mark it!", :class => "button" %>
<% end %>

app/views/geomarkers/_geomarker_form_errors.html.erb
<% if @geomarker.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% for message in @geomarker.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/geomarkers/_new_form.html.erb
<div id='geomarker-form-errors'></div>
<%= form_for @geomarker, :html => { :multipart => true, :target => "blank_iframe" }, :remote => true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label "Description" %>
  <%= f.text_area :description %>
  <br>
  <%= f.label "Tags (a comma separated list)" %>
  <%= f.text_field :tag_list %>
  <br>
  <%= f.hidden_field :latitude, :value => params[:geomarker][:latitude] %>
  <%= f.hidden_field :longitude, :value => params[:geomarker][:longitude] %>
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <%= f.label :image %>
  <%= f.file_field :image %>
  <hr>
  <input id="cancelFormButton" class="button small" type="button" value="Cancel"/>
  <%= f.submit "Submit", :class => "button small", :id => "submit" %>
<% end %>

app/views/geomarkers/_review_form_errors.html.erb
<% if @comment.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% for message in @comment.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/geomarkers/_show.html.erb
<!-- Geomarker options buttons -->
<ul class="showOptions">
  <li>
  <% if current_user.id == @geomarker.user_id %>
    <input id="optionsButton" type="button" value="Options" />
    <ul id="optionsMenu">
      <li><a id="editButton" href="#">Edit</a></li>
      <li><a id="deleteButton" href="#">Delete</a></li>
    </ul>
  <% end %>
  </li>
  <li>
    <input id="closeShowButton" type="button" value="Close"/>
  </li>
</ul>
<hr>
<!-- Geomarker information display -->
<h2><%= @geomarker.name %></h2>
<p><%= @geomarker.description %></p>
<br>
<% if @geomarker.image %>
  <% if params[:windowWidth].to_f < 40 %>
    <%= image_tag @geomarker.image.thumb.to_s %>
  <% elsif params[:windowWidth].to_f >= 40 && params[:windowWidth].to_f < 60 && @geomarker.image.medium %>
    <%= image_tag @geomarker.image.medium.to_s %>
  <% elsif params[:windowWidth].to_f >= 60 && @geomarker.image.large %>
    <%= image_tag @geomarker.image.large.to_s %>
  <% else %>
    <%= image_tag @geomarker.image.to_s %>
  <% end %>
<% end %>
<br>
<!-- Display tags -->
<p>Created by: <a class="friendProfileButton" href="#" data-id="<%= @user.id %>"><%= @user.username %></a></p>
<% if @geomarker.tags.any? %>
 <p>Tags: <span class="tag-list"><%= @geomarker.tag_list %></span> </p>
<% end %>
<a id="addTagButton" href="#">Add tags</a>

<div class="new-tag-bar">
  <div class="new-tag-wrapper">
    <div class="newTags">
      <input type="text" id="new-geomarker-tags"></input>
    </div>
    <div class="tagSubmitButton">
      <a href="#" id="tagSubmit">Add</a>
    </div>
  </div>
</div>

<!-- Comment form -->
<%= form_for [@geomarker, @comment], :remote => true do |f| %>
  <div id="comment-form-errors" >  
    <%= render :partial => "comment_form_errors" %>
  </div>
  <%= f.label "Add a Comment" %>
  <%= f.text_area :content %>
  <%= f.submit "Post", :class => "button centered"%></p>
<% end %>

<!-- Comment display -->
<h3 id="comment-header">
<% if @geomarker.comments.length > 1 %>
  What people've been saying:
<% else %>
  Be the first to comment.
<% end %>
</h3>
<div id="comment-display">
  <%= render :partial => "comments" %>
</div>

app/views/geomarkers/destroy.js.erb
enableMap();
removeGeomarkerShow();

app/views/geomarkers/edit.html.erb
<h1>Edit Geomarker</h1>
<%= render 'geomarker_form' %>

app/views/geomarkers/index.html.erb
<h1>Geomarkers</h1>

<%= link_to "Markers in your Collections", geomarkers_path(:view => "collection"), class: "button" %>

<% if current_user %>
  <%= link_to "Sign out", signout_path, class: "button" %>
  <%= link_to "YOU", user_path(current_user.id), class: "button" %>
<% else %>
  <%= link_to "Sign up", signup_path %>
  <%= link_to "Sign in", signin_path %>
<% end %>
<%= link_to "New Marker!", new_geomarker_path, class: "button" %>
<br>

<div style="width: 300px">
  <%= form_tag geomarkers_path, :method => "get" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil, class: "button small" %>
    <div style="width: 80px">
      <%= select_tag(:option, options_for_select([["Any", 1], ["All", 2]])) %>
    </div>

  </p>
<% end %>

</div>


<% if params[:tag].present? %>
    <h2>Geomarkers tagged with <%= params[:tag] %></h2>
<% elsif params[:search].present? %>
    <h2>Geomarkers tagged with <%= params[:search] %></h2>
<% else %>
    <h2>All Geomarkers</h2>
<% end %>
<br>
<% @geomarkers.each do |geomarker| %>
  <p><%= link_to geomarker.name, geomarker_path(geomarker) %>
    <span><%= geomarker.tag_list %>|</span>
    <span><%= geomarker.description %></span>
    <span><%= geomarker.latitude %></span>
  <span><%= geomarker.longitude %></span>
  </p>

<% end %>

app/views/geomarkers/new.html.erb
<h1>Add a Geomarker</h1>
<%= render 'geomarker_form' %>

app/views/geomarkers/new.js.erb
$(".form-container").append("<div class='geomarker-form'><%= j render 'geomarkers/new_form' %></div><iframe id='blank_iframe' name='blank_iframe'><div id='map'></div></iframe>");

$("#cancelFormButton").on("click", function(){
  enableMap();
  $("#new-marker-button").trigger("click");
  removeGeomarkerForm();
  removeIFrame();
});
$("#new_geomarker").on("submit", function(){
  $("#submit").val("Uploading...");
  $("#blank_iframe").on("load", function(){
    var errors = extractIFrameErrors();
    if (errors){
      $("#blank_iframe").off();
      $("#geomarker-form-errors").empty();
      $("#geomarker-form-errors").append(errors);
      $("#submit").val("Submit");
    } else {
      getNewMarker();
      removeIFrame();
      updateMap();
      $("#new-marker-button").trigger("click");
      removeGeomarkerForm();
    }
  });
});

app/views/geomarkers/show.html.erb
<h2><%= @geomarker.name %></h2>
<h5><%= @geomarker.tag_list %></h5>
<p><%= @geomarker.description %></p>
<p>Latitude: <%= @geomarker.latitude %></p>
<p>Longitude: <%= @geomarker.longitude %></p>
<br>
<% if @geomarker.image %>
  <%= image_tag @geomarker.image_url(:thumb).to_s %>
  <%= image_tag @geomarker.image.to_s %>
<% end %>
<br>
<p>Created by: <%= link_to @user.username, user_path(@user) %></p>
<% if @geomarker.tags.any? %>
 <p>Tags: <% @geomarker.tags.each do |tag| %>
   <span><%= link_to tag.name, geomarkers_path(:tag => tag.name) %></span>
   <% end %>
 </p>
<% end %>
<%= link_to "Home", geomarkers_path, :class => "button" %>
<%= link_to "Edit Geomarker", edit_geomarker_path(@geomarker), :class => "button" %>
<%= link_to "Delete", @geomarker, method: :delete, :class => "button" %>

app/views/geomarkers/update.js.erb
<% if @geomarker.errors.any? %>
  $('#geomarker-form-errors').html('<%= escape_javascript(render "geomarker_form_errors") %>' );
<% elsif @new_tags %>
  var id = <%= @geomarker.id %>;
  removeMarker(id);
  updateMarker(id);
  $(".tag-list").empty();
  $(".tag-list").append("<%= @geomarker.tag_list %>");
  $("#new-geomarker-tags").val("");
  $("#addTagButton").trigger("click");
<% else %>
  var id = <%= @geomarker.id %>;
  removeMarker(id);
  updateMarker(id);
  
  // with exception of getGeomarkerShow(), each of the following methods contains control flow to adapt to circumstances of update
  removeIFrame();
  removeGeomarkerShow();
  removeGeomarkerForm();
  getGeomarkerShow(id);
<% end %>